name: Node.js CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        # This will allow caching for both server and client
        cache: 'npm'
        cache-dependency-path: |
          server/package-lock.json
          client/package-lock.json

    # Install and test server
    - name: Install Server Dependencies
      run: npm ci
      working-directory: ./server
    - name: Build Server
      run: npm run build --if-present
      working-directory: ./server
      # Server test needs vpn connection so therefore they are not run
      # run: npm test
    - name: Test Server
      run: node -e "console.log('Server test needs vpn connection so therefore they are not run')"
      working-directory: ./server

    # Install and test client
    - name: Install Client Dependencies
      run: npm ci
      working-directory: ./client
    - name: Build Client
      run: npm run build --if-present
      working-directory: ./client
    - name: Test Client
      run: npm test
      working-directory: ./client